#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

case "$1" in

  sandstorm:create-volume)
    [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
    [[ -z $3 ]] && dokku_log_fail "Please specify an folder to make persistent, e.g. /app/Data/Persistent"
    APP="$2"; FOLDER="$3"

    # remove slash on left and right side of folder
    FOLDER=${FOLDER%/}
    FOLDER=${FOLDER#/}

    verify_app_name "$APP"

    APP_DATA_DIR="${DOKKU_ROOT}/${APP}/DATA"
    mkdir -p "$APP_DATA_DIR/$FOLDER"
    chown -R dokku "$APP_DATA_DIR/$FOLDER"


    dokku docker-options:add $APP deploy "-v $APP_DATA_DIR/$FOLDER:/$FOLDER"
    dokku docker-options:add $APP run "-v $APP_DATA_DIR/$FOLDER:/$FOLDER"
    dokku docker-options $APP

    ;;

  sandstorm:remove-volume)

    [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
    [[ -z $3 ]] && dokku_log_fail "Please specify an folder to remove, e.g. /app/Data/Persistent"
    APP="$2"; FOLDER="$3"

    # remove slash on left and right side of folder
    FOLDER=${FOLDER%/}
    FOLDER=${FOLDER#/}

    verify_app_name "$APP"

    dokku docker-options:remove $APP deploy "-v $APP_DATA_DIR/$FOLDER:/$FOLDER"
    dokku docker-options:remove $APP run "-v $APP_DATA_DIR/$FOLDER:/$FOLDER"
    dokku docker-options $APP

    ;;

  sandstorm:copy)

    [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
    [[ -z $3 ]] && dokku_log_fail "Please specify a target app"
    APP="$2"; TARGET_APP="$3"

    verify_app_name "$APP"

    check_app_name "$3"
    [[ -d "$APP_DIR/refs" ]] && fail "target $APP: already exists; so cannot copy to that."
    ;;

  help)
    cat<<EOF
    sandstorm:create-volume <app> <folder>
    sandstorm:remove-volume <app> <folder>
    sandstorm:copy <app> <destination>
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
